name: cd

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v5
        with:
          name: projetozipado.zip
          path: |
            **.py
            README.md
          
  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: projeto.zip
      - name: Display structure of downloaded files
        run: ls -R

  docker:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        #name: Login to Docker Hub
          #uses: docker/login-action@v3
          #with:
            #username: ${{ secrets.DOCKERHUB_USERNAME }}
            #password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: false
                tags: user/app:latest